### ISSUE TITLE
[ReuseIR] Support recusive type

### ISSUE THREAD

**Issue by SchrodingerZhu** [SchrodingerZhu/ReuseIR#17]
See https://mlir.llvm.org/docs/DefiningDialects/AttributesAndTypes/#defining-a-mutable-storage.
We want to allow a type to refer to it self across `rc/mref`. So we will need to customize how we print/parse such types.

Could you take a look at this? @Lancern  I am okay with any syntax design.

**Comment by Lancern** [comment]
> We want to allow a type to refer to it self across rc/mref.

Such a type must be either a composite type or a union type. If we could give these type a `name` parameter:

```mlir
!reuse_ir.composite<"name", members...>
!reuse_ir.union<"name", members...>
```

Then recursive type could be represented as:

```mlir
!reuse_ir.composite<"name", members..., !reuse_ir.rc<!reuse_ir.composite<"name">>, members...>
!reuse_ir.union<"name", members..., !reuse_ir.rc<!reuse_ir.union<"name">>, members...>
```

**Comment by SchrodingerZhu** [comment]
Sure, I am okay with named types.

**Comment by SchrodingerZhu** [comment]
@Lancern I think we should go with https://github.com/llvm/clangir/pull/303
