### ISSUE TITLE
[ReuseIR] add `reuse_ir.func`

### ISSUE THREAD

**Issue by SchrodingerZhu** [SchrodingerZhu/ReuseIR#9]
It seems that `func.func` does not handle C/C++-like call convention automatically (in fact, it shouldn't). Therefore, we'd better provide our wrapper of functions.

@Lancern could you take a took at this? For now, adding basic syntax support is sufficient but we ultimately want a wrapper that help us to transform calls as if in C/C++.

**Comment by Lancern** [comment]
What is the use case of `reuse_ir.func`, especially the calling convention part as mentioned? I thought ReuseIR is language agnostic.

**Comment by SchrodingerZhu** [comment]
Fair enough. I guess it is up to the frontend's responsibility to handle it? We already have `reuse_ir.val2ref` so I guess frontend can already emit it.
